# Station Configuration
# The 'coordinates' dictionary is now the single source of truth for all active stations.
stations:
  coordinates:
    # --- Corrected & Expanded Pacific Stations ---
    "41001": [34.686, -72.664] # East Coast Reference
    "42001": [25.866, -89.658] # Gulf of Mexico Reference
    "44013": [42.346, -70.651] # Boston
    "44025": [40.251, -73.164] # New York
    "44027": [43.177, -70.430] # Jonesport, ME
    "46012": [37.359, -122.880] # Half Moon Bay, CA
    "46013": [38.234, -123.319] # Bodega Bay, CA
    "46014": [39.222, -123.978] # Point Arena, CA
    "46022": [40.750, -124.500] # Eel River, CA
    "46026": [37.755, -122.854] # San Francisco, CA
    "46027": [35.705, -121.879] # Cape San Martin, CA
    "46042": [36.785, -122.398] # Monterey Bay, CA (Corrected from 46001)
    "46054": [34.269, -120.453] # West Santa Barbara, CA
    "46059": [38.044, -123.031] # Point Reyes, CA
    "46086": [33.750, -119.060] # San Clemente Basin, CA
    "46232": [34.938, -120.869] # Point Arguello, CA

    # --- Corrected & Expanded Hawaiian Stations ---
    "51001": [23.427, -162.301] # NW Hawaii
    "51002": [17.158, -157.798] # Hilo, HI
    "51003": [21.842, -159.392] # S Kauai, HI
    "51101": [24.292, -162.062] # N Hawaii

# Data Paths
data_paths:
  historical_archive: "data/historical_archive"
  processed_features: "data/processed/historical_features.parquet"
  models: "data/models"

# Processor Configuration
processor:
  freq_bins:
    [
      0.030,
      0.035,
      0.040,
      0.045,
      0.050,
      0.055,
      0.060,
      0.065,
      0.070,
      0.075,
      0.080,
      0.085,
      0.090,
      0.095,
      0.100,
      0.105,
      0.110,
      0.115,
      0.120,
      0.125,
      0.130,
      0.135,
      0.140,
      0.145,
      0.150,
      0.155,
      0.160,
      0.165,
      0.170,
      0.175,
      0.180,
      0.185,
      0.190,
      0.195,
      0.200,
      0.205,
      0.210,
      0.215,
      0.220,
      0.225,
      0.230,
      0.235,
      0.240,
      0.245,
      0.250,
      0.255,
      0.260,
      0.265,
      0.270,
      0.275,
      0.280,
      0.285,
      0.290,
      0.295,
      0.300,
      0.305,
      0.310,
      0.315,
      0.320,
      0.325,
      0.330,
      0.335,
      0.340,
      0.345,
      0.350,
      0.355,
      0.360,
      0.365,
      0.370,
      0.375,
      0.380,
      0.385,
      0.390,
      0.395,
      0.400,
      0.405,
      0.410,
      0.415,
      0.420,
      0.425,
      0.430,
      0.435,
      0.440,
      0.445,
      0.450,
      0.455,
      0.460,
      0.465,
      0.470,
      0.475,
      0.480,
      0.485,
    ]
  max_time_gap: "30min"

# Model Architecture
model:
  d_model: 256
  num_layers: 6
  num_heads: 8
  distance_threshold_km: 500
  freq_bins: 32

# Training Configuration
training:
  seq_length: 72
  pred_horizon: 24
  batch_size: 32
  num_workers: 4
  train_split: "2020-12-31"
  val_split: "2021-07-01"
  learning_rate: 1e-4
  weight_decay: 1e-5
